# Generated by Django 4.2.2 on 2025-06-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Dentistry', 'Dentistry'), ('Orthopedics', 'Orthopedics'), ('ENT', 'ENT'), ('Oncology', 'Oncology'), ('General', 'General'), ('Radiology', 'Radiology'), ('Urology', 'Urology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Nephrology', 'Nephrology'), ('Rheumatology', 'Rheumatology'), ('Pulmonology', 'Pulmonology'), ('Ophthalmology', 'Ophthalmology')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
